name: test

on: [push]

jobs:
  test-js:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./ui

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Packages
      run: npm ci

    - name: Run Tests
      run: npm run test
